#!/bin/sh
cd ${0%/*} || exit 1    # run from this directory

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

rm -rf 0/alpha.water 0/H 0/M

cleanCase

# cleanCase deletes all files that are used to
#   open the case in paraFoam/paraview, restore
#   these files
touch case.foam
touch case.blockMesh
touch case.OpenFOAM

